import type { MuscleGroup } from '@/types'

export interface ExerciseEntry {
  id: string
  name: string
  primary_muscle: MuscleGroup
  secondary_muscles: MuscleGroup[]
  description: string
  image_url: string | null
  youtube_url: string | null
  category: 'strength' | 'cardio' | 'flexibility'
}

export const EXERCISES: ExerciseEntry[] = [
  // ── CHEST ────────────────────────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower it to your chest, and press back up.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    category: 'strength',
  },
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Set bench to 30-45°. Press dumbbells up from chest level, focusing on the upper chest.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    category: 'strength',
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms', 'core'],
    description: 'Classic bodyweight push-up. Keep your body in a straight line from head to heels.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    category: 'strength',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    description: 'Set cables at chest height. Bring handles together in a wide arc, squeezing the chest at the peak.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
    category: 'strength',
  },
  {
    id: 'dips',
    name: 'Chest Dips',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Lean forward slightly on the dip bars to target the chest. Lower until arms are at 90°.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=wjUmnZH528Y',
    category: 'strength',
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Lie on a flat bench, press dumbbells up from chest level with a neutral or pronated grip.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-decline-bench-press',
    name: 'Dumbbell Decline Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Press dumbbells on a decline bench to emphasize the lower chest.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-floor-press',
    name: 'Dumbbell Floor Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Lie on the floor and press dumbbells up. The floor limits range of motion, reducing shoulder stress.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-squeeze-press',
    name: 'Dumbbell Squeeze Press',
    primary_muscle: 'chest',
    secondary_muscles: ['arms'],
    description: 'Press dumbbells together throughout the movement to maximize chest contraction.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-incline-bench-press',
    name: 'Dumbbell Incline Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Press dumbbells on an incline bench set to 30-45° to target the upper chest.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    description: 'Lie on a flat bench, open arms wide with a slight bend in elbows, then squeeze dumbbells together.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-crossover-fly',
    name: 'Cable Crossover Fly',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    description: 'Use high or low cable pulleys to bring handles together in a crossing arc for constant chest tension.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'machine-fly',
    name: 'Machine Fly',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    description: 'Sit in the pec deck machine and bring the pads together, squeezing the chest.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'machine-bench-press',
    name: 'Machine Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Press handles forward on a chest press machine. Good for controlled, guided movement.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'smith-machine-bench-press',
    name: 'Smith Machine Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Bench press on a Smith machine for a guided bar path and added stability.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'smith-machine-incline-bench-press',
    name: 'Smith Machine Incline Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Incline bench press on a Smith machine to target upper chest with a guided bar path.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'hammerstrength-incline-chest-press',
    name: 'Hammerstrength Incline Chest Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Plate-loaded incline press machine that allows independent arm movement.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'decline-push-up',
    name: 'Decline Push Up',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms', 'core'],
    description: 'Push-up with feet elevated on a bench or step to increase upper chest and shoulder engagement.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dip',
    name: 'Dip',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Bodyweight dip on parallel bars. Lean forward for chest emphasis or stay upright for triceps.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'bench-dip',
    name: 'Bench Dip',
    primary_muscle: 'chest',
    secondary_muscles: ['arms', 'shoulders'],
    description: 'Place hands on a bench behind you, lower body by bending elbows, then press back up.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },

  // ── BACK ─────────────────────────────────────────────────────────────────
  {
    id: 'pull-up',
    name: 'Pull-Up',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Hang from a bar with overhand grip. Pull yourself up until chin clears the bar.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    category: 'strength',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms', 'core'],
    description: 'Hinge at hips, keep back flat, pull bar to lower chest. One of the best back builders.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ',
    category: 'strength',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Pull the bar down to upper chest level, leading with elbows. Wide grip targets the lats.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    category: 'strength',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Sit upright, pull the cable handle to your midsection, squeezing shoulder blades together.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    category: 'strength',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    primary_muscle: 'back',
    secondary_muscles: ['legs', 'core'],
    description: 'Pull the barbell from the floor to hip level. Engages the entire posterior chain.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    category: 'strength',
  },
  {
    id: 'bent-over-barbell-row',
    name: 'Bent Over Barbell Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms', 'core'],
    description: 'Hinge at the hips and row a barbell to your lower chest. Builds overall back thickness.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Row a dumbbell to your hip with one arm, bracing the other on a bench.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'incline-dumbbell-row',
    name: 'Incline Dumbbell Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Lie chest-down on an incline bench and row dumbbells up to reduce momentum and isolate the back.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'landmine-row',
    name: 'Landmine Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms', 'core'],
    description: 'Row the end of a barbell anchored in a landmine attachment for a unique pulling angle.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'pendlay-row',
    name: 'Pendlay Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms', 'core'],
    description: 'Strict barbell row from a dead stop on the floor each rep. Builds explosive back strength.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'reverse-grip-barbell-bent-over-row',
    name: 'Reverse Grip Barbell Bent Over Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Bent-over row with an underhand grip to emphasize the lower lats and biceps.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'smith-machine-bent-over-row',
    name: 'Smith Machine Bent Over Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Bent-over row using a Smith machine for a guided bar path.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'shotgun-row',
    name: 'Shotgun Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms', 'core'],
    description: 'Single-arm cable row with a staggered stance, pulling the handle to your side.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'inverted-row',
    name: 'Inverted Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms', 'core'],
    description: 'Hang beneath a bar and pull your chest up to it. A bodyweight horizontal pull.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'australian-chin-up',
    name: 'Australian Chin Up',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Bodyweight row performed under a low bar with feet on the ground. Great for beginners.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'assisted-pull-up',
    name: 'Assisted Pull Up',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Pull-up using a machine or band for assistance to reduce bodyweight load.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-row',
    name: 'Cable Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Pull a cable handle toward your torso while seated or standing. Constant tension on the back.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-row-wide',
    name: 'Cable Row Wide',
    primary_muscle: 'back',
    secondary_muscles: ['arms', 'shoulders'],
    description: 'Wide-grip cable row to emphasize the upper back and rear delts.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'wide-grip-lat-pulldown',
    name: 'Wide Grip Lat Pulldown',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Lat pulldown with a wider-than-shoulder grip to maximize lat stretch and contraction.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'reverse-grip-pull-down',
    name: 'Reverse Grip Pull Down',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Lat pulldown with an underhand grip to increase bicep involvement and lower lat activation.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'barbell-shrug',
    name: 'Barbell Shrug',
    primary_muscle: 'back',
    secondary_muscles: ['shoulders'],
    description: 'Hold a barbell at arm\'s length and shrug your shoulders up toward your ears. Targets the traps.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-shrug',
    name: 'Dumbbell Shrug',
    primary_muscle: 'back',
    secondary_muscles: ['shoulders'],
    description: 'Hold dumbbells at your sides and shrug shoulders up. Great for building the trapezius.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-face-pull',
    name: 'Cable Face Pull',
    primary_muscle: 'back',
    secondary_muscles: ['shoulders'],
    description: 'Pull a rope attachment to face level with external rotation. Targets rear delts and rotator cuff.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-back-fly',
    name: 'Dumbbell Back Fly',
    primary_muscle: 'back',
    secondary_muscles: ['shoulders'],
    description: 'Bent over, raise dumbbells out to the sides to target the rear delts and upper back.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-rear-delt-raise',
    name: 'Dumbbell Rear Delt Raise',
    primary_muscle: 'back',
    secondary_muscles: ['shoulders'],
    description: 'Raise dumbbells to the sides while bent forward to isolate the rear deltoids.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'machine-rear-delt-fly',
    name: 'Machine Rear Delt Fly',
    primary_muscle: 'back',
    secondary_muscles: ['shoulders'],
    description: 'Sit facing the pec deck machine and push handles apart to work the rear delts.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-shoulder-external-rotation',
    name: 'Cable Shoulder External Rotation',
    primary_muscle: 'back',
    secondary_muscles: ['shoulders'],
    description: 'Externally rotate the shoulder against cable resistance. Important for rotator cuff health.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },

  // ── LEGS ─────────────────────────────────────────────────────────────────
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Bar on traps, squat to parallel or below. The king of leg exercises.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    category: 'strength',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Press the platform away with both feet at shoulder-width. Control the descent.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    category: 'strength',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    primary_muscle: 'legs',
    secondary_muscles: ['back'],
    description: 'Hinge at hips with soft knees, lowering the bar along your legs. Great for hamstrings.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    category: 'strength',
  },
  {
    id: 'lunges',
    name: 'Dumbbell Lunges',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Step forward into a lunge, lowering the back knee toward the floor. Alternate legs.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
    category: 'strength',
  },
  {
    id: 'leg-curl',
    name: 'Lying Leg Curl',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Curl your heels toward your glutes against resistance. Isolates the hamstrings.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
    category: 'strength',
  },
  {
    id: 'air-squats',
    name: 'Air Squats',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Bodyweight squat performed with no added resistance. Great for warm-ups and conditioning.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'bodyweight-squat-hold',
    name: 'Bodyweight Squat Hold',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Hold the bottom position of a bodyweight squat to build isometric leg strength and mobility.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-squat',
    name: 'Dumbbell Squat',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Hold dumbbells at your sides or shoulders and perform a squat.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-sumo-squat',
    name: 'Dumbbell Sumo Squat',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Wide-stance squat holding a dumbbell between your legs. Targets inner thighs and glutes.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-bulgarian-split-squat',
    name: 'Dumbbell Bulgarian Split Squat',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Single-leg squat with rear foot elevated on a bench. Builds unilateral leg strength.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-lunge',
    name: 'Dumbbell Lunge',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Step forward holding dumbbells and lower into a lunge. Alternate legs each rep.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-walking-lunge',
    name: 'Dumbbell Walking Lunge',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Perform continuous lunges while walking forward with dumbbells in each hand.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'lateral-lunge-stretch',
    name: 'Lateral Lunge Stretch',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Step to the side into a deep lunge to stretch and strengthen the inner thighs.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'heels-up-goblet-squat-pregnancy',
    name: 'Heels Up Goblet Squat (Pregnancy)',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Goblet squat with heels elevated on a plate. Pregnancy-friendly variation for quad emphasis.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'smith-machine-squat',
    name: 'Smith Machine Squat',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Squat using a Smith machine for a guided bar path and added stability.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Extend your legs against resistance on a leg extension machine. Isolates the quadriceps.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'lying-hamstrings-curl',
    name: 'Lying Hamstrings Curl',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Lie face down and curl the pad toward your glutes. Isolates the hamstrings.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'machine-leg-press',
    name: 'Machine Leg Press',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Press the platform on a leg press machine. Targets quads, glutes, and hamstrings.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Sit with upper back on a bench, barbell over hips, and thrust hips upward. Great for glutes.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'smith-machine-glute-bridge',
    name: 'Smith Machine Glute Bridge',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Glute bridge using a Smith machine bar for added resistance and stability.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'smith-machine-stiff-legged-deadlift',
    name: 'Smith Machine Stiff-Legged Deadlift',
    primary_muscle: 'legs',
    secondary_muscles: ['back'],
    description: 'Stiff-legged deadlift on a Smith machine to target hamstrings with a guided bar path.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    primary_muscle: 'legs',
    secondary_muscles: ['back'],
    description: 'Hinge at hips with dumbbells, keeping legs mostly straight. Targets hamstrings and glutes.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-hip-adduction',
    name: 'Cable Hip Adduction',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Pull your leg inward against cable resistance. Targets the inner thigh adductors.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-hip-extension',
    name: 'Cable Hip Extension',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Kick your leg backward against cable resistance. Targets the glutes.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-pull-through',
    name: 'Cable Pull Through',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Face away from the cable, hinge forward, and thrust hips to pull the cable through your legs.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'single-leg-kickback',
    name: 'Single Leg Kickback',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Kick one leg back against resistance to isolate the glutes.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'clam',
    name: 'Clam',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Lie on your side, knees bent, and open knees apart like a clamshell. Activates the glute medius.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'seated-dumbbell-calf-raise',
    name: 'Seated Dumbbell Calf Raise',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Sit with dumbbells on your knees and raise your heels to work the soleus muscle.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'seated-machine-calf-press',
    name: 'Seated Machine Calf Press',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Push through the balls of your feet on a seated calf machine. Targets the soleus.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'smith-machine-calf-raise',
    name: 'Smith Machine Calf Raise',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Stand on a platform under a Smith machine bar and raise your heels for calf development.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'single-leg-standing-calf-raise',
    name: 'Single Leg Standing Calf Raise',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Stand on one foot and raise your heel. Unilateral calf exercise for balanced development.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Lean against a wall with knees at 90°. Isometric hold that builds quad endurance.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    primary_muscle: 'legs',
    secondary_muscles: ['back', 'core'],
    description: 'Wide-stance deadlift with hands inside the knees. Emphasizes the inner thighs and glutes.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'stair-stepper',
    name: 'Stair Stepper',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Cardio machine that simulates climbing stairs. Builds leg endurance and burns calories.',
    image_url: null,
    youtube_url: null,
    category: 'cardio',
  },

  // ── SHOULDERS ────────────────────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Barbell Overhead Press',
    primary_muscle: 'shoulders',
    secondary_muscles: ['arms', 'core'],
    description: 'Press a barbell from shoulder height straight overhead. Keep core braced throughout.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    category: 'strength',
  },
  {
    id: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: [],
    description: 'Raise dumbbells out to the sides to shoulder height. Targets the medial (side) delt.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    category: 'strength',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    primary_muscle: 'shoulders',
    secondary_muscles: ['back'],
    description: 'Pull a rope attachment to face level, externally rotating shoulders. Great for rear delts.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    category: 'strength',
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    primary_muscle: 'shoulders',
    secondary_muscles: ['arms'],
    description: 'Start with dumbbells at chin with palms facing you, rotate and press overhead.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=6Z15_WdXmVw',
    category: 'strength',
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    primary_muscle: 'shoulders',
    secondary_muscles: ['arms'],
    description: 'Press dumbbells overhead from shoulder height. Can be performed seated or standing.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    primary_muscle: 'shoulders',
    secondary_muscles: ['arms'],
    description: 'Press handles overhead on a shoulder press machine for guided, stable movement.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: [],
    description: 'Raise dumbbells out to the sides to shoulder height. Isolates the medial deltoid.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: [],
    description: 'Lateral raise using a low cable for constant tension throughout the range of motion.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-hanging-lateral-raise',
    name: 'Dumbbell Hanging Lateral Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: [],
    description: 'Lean away from a support and perform a lateral raise for increased range of motion.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-front-raise',
    name: 'Dumbbell Front Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: ['chest'],
    description: 'Raise dumbbells in front of you to shoulder height. Targets the anterior deltoid.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'barbell-front-raise',
    name: 'Barbell Front Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: ['chest'],
    description: 'Raise a barbell in front of you to shoulder height. Targets the front delts.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'front-plate-raise',
    name: 'Front Plate Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: ['chest', 'core'],
    description: 'Hold a weight plate and raise it in front of you to shoulder height or above.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },

  // ── ARMS ─────────────────────────────────────────────────────────────────
  {
    id: 'bicep-curl',
    name: 'Dumbbell Bicep Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl the dumbbells from fully extended to fully contracted, keeping elbows fixed.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    category: 'strength',
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Push a cable bar or rope down until arms are fully extended. Keep elbows at sides.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=2-LAMcpzODU',
    category: 'strength',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Neutral grip curl (thumbs up). Targets both bicep and brachialis for thicker arms.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
    category: 'strength',
  },
  {
    id: 'skull-crushers',
    name: 'Skull Crushers',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Lower a barbell or dumbbells toward your forehead while lying on a bench. Tricep isolation.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
    category: 'strength',
  },
  {
    id: 'dumbbell-bicep-curl',
    name: 'Dumbbell Bicep Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl dumbbells from full extension to contraction, keeping elbows pinned at your sides.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Sit and brace your elbow against your inner thigh, curling a dumbbell for peak bicep contraction.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'ez-bar-curl',
    name: 'EZ-Bar Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl an EZ-bar with an angled grip that reduces wrist strain while targeting the biceps.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'ez-bar-reverse-grip-curl',
    name: 'EZ-Bar Reverse Grip Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl an EZ-bar with an overhand grip to target the brachioradialis and forearms.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'reverse-barbell-curl',
    name: 'Reverse Barbell Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl a barbell with an overhand grip. Targets the brachioradialis and forearm extensors.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl dumbbells while seated on an incline bench for a greater bicep stretch at the bottom.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'incline-ez-bar-curl',
    name: 'Incline EZ-Bar Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl an EZ-bar while lying back on an incline bench for increased bicep stretch.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'machine-bicep-curl',
    name: 'Machine Bicep Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl against resistance on a bicep curl machine. Provides consistent tension throughout.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'handle-band-bicep-curl',
    name: 'Handle Band Bicep Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl using a resistance band with handles for portable bicep training.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-rope-hammer-curls',
    name: 'Cable Rope Hammer Curls',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl a rope attachment with a neutral grip on the cable machine. Targets biceps and brachialis.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cross-body-hammer-curls',
    name: 'Cross Body Hammer Curls',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl a dumbbell across your body with a neutral grip to emphasize the brachialis.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'hammer-curls',
    name: 'Hammer Curls',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl dumbbells with a neutral (thumbs-up) grip. Targets both the biceps and brachialis.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-tricep-pushdown',
    name: 'Cable Tricep Pushdown',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Push a cable bar or rope downward until arms are fully extended. Isolates the triceps.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-rope-tricep-extension',
    name: 'Cable Rope Tricep Extension',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Push a rope attachment down and apart at the bottom to fully contract the triceps.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-one-arm-tricep-side-extension',
    name: 'Cable One Arm Tricep Side Extension',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Single-arm tricep extension using a cable, pushing down and to the side.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-tricep-extension',
    name: 'Dumbbell Tricep Extension',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Hold a dumbbell overhead and lower it behind your head, then extend back up. Targets the long head.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-kickbacks',
    name: 'Dumbbell Kickbacks',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Hinge forward and extend a dumbbell behind you, squeezing the triceps at full extension.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dumbbell-skullcrusher',
    name: 'Dumbbell Skullcrusher',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Lower dumbbells toward your forehead while lying on a bench, then extend. Tricep isolation.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'cable-wrist-curl',
    name: 'Cable Wrist Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl your wrist upward against cable resistance. Targets the forearm flexors.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'palms-down-dumbbell-wrist-curl',
    name: 'Palms-Down Dumbbell Wrist Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Wrist extension with dumbbells, palms facing down. Targets the forearm extensors.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'palms-up-barbell-wrist-curl',
    name: 'Palms-Up Barbell Wrist Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Wrist curl with a barbell, palms facing up. Targets the forearm flexors.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'palms-up-dumbbell-wrist-curl',
    name: 'Palms-Up Dumbbell Wrist Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Wrist curl with dumbbells, palms facing up. Isolates the forearm flexors.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },

  // ── CORE ─────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    primary_muscle: 'core',
    secondary_muscles: ['shoulders'],
    description: 'Hold a push-up position on your forearms. Keep hips level and core tight.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    category: 'strength',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Hang from a bar, raise straight legs to 90° (or higher). Targets lower abs.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
    category: 'strength',
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Kneel at a cable with rope attachment overhead, crunch down contracting abs.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=2fbujeH3F0E',
    category: 'strength',
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    primary_muscle: 'core',
    secondary_muscles: ['shoulders', 'back'],
    description: 'Roll the wheel out from kneeling position, extending body, then pull back. Advanced core.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=wbsKrGkIx1A',
    category: 'strength',
  },
  {
    id: 'ab-crunch-machine',
    name: 'Ab Crunch Machine',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Crunch against resistance on a machine. Provides controlled, weighted ab training.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'alternating-heel-touch',
    name: 'Alternating Heel Touch',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie on your back with knees bent, alternate reaching each hand to the same-side heel. Targets obliques.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Alternate bringing opposite elbow to knee in a pedaling motion. Works abs and obliques.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'copenhagen-plank',
    name: 'Copenhagen Plank',
    primary_muscle: 'core',
    secondary_muscles: ['legs'],
    description: 'Side plank with top leg on a bench. Targets adductors and obliques simultaneously.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'crunches',
    name: 'Crunches',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie on your back and curl your shoulders off the floor. A classic ab exercise.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie on your back, extend opposite arm and leg while keeping your lower back pressed into the floor.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie on your back, lift arms, shoulders, and legs off the floor. Isometric core hold.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    primary_muscle: 'core',
    secondary_muscles: ['legs', 'shoulders'],
    description: 'Skip rope for cardio conditioning. Improves coordination, footwork, and endurance.',
    image_url: null,
    youtube_url: null,
    category: 'cardio',
  },
  {
    id: 'leg-pull-in',
    name: 'Leg Pull-In',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Sit on a bench edge, lean back slightly, and pull knees toward your chest. Targets lower abs.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'leg-raise',
    name: 'Leg Raise',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie flat and raise straight legs to 90°. Targets the lower abdominals.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    primary_muscle: 'core',
    secondary_muscles: ['shoulders', 'legs'],
    description: 'In a push-up position, drive knees alternately toward your chest at a quick pace.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'oblique-crunch',
    name: 'Oblique Crunch',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Crunch with a twist to one side to target the oblique muscles.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'plank-shoulder-taps',
    name: 'Plank Shoulder Taps',
    primary_muscle: 'core',
    secondary_muscles: ['shoulders'],
    description: 'In a high plank, alternate tapping each shoulder with the opposite hand. Anti-rotation core work.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'reverse-crunch',
    name: 'Reverse Crunch',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie on your back, curl hips and knees toward your chest. Emphasizes lower abs.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Sit with torso leaned back, rotate side to side with or without weight. Targets obliques.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'scissor-crossover-kick',
    name: 'Scissor Crossover Kick',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie on your back, legs raised, cross legs over each other in an alternating scissor motion.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'scissor-kick',
    name: 'Scissor Kick',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie on your back and alternate kicking legs up and down in a flutter motion. Targets lower abs.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'side-bridge',
    name: 'Side Bridge',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Side plank variation held on your forearm. Targets the obliques and lateral core.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'sit-up',
    name: 'Sit Up',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Lie on your back with knees bent, sit all the way up. Full range ab exercise.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'superman',
    name: 'Superman',
    primary_muscle: 'core',
    secondary_muscles: ['back'],
    description: 'Lie face down, simultaneously lift arms, chest, and legs off the floor. Targets the lower back.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'superman-hold',
    name: 'Superman Hold',
    primary_muscle: 'core',
    secondary_muscles: ['back'],
    description: 'Hold the superman position with arms, chest, and legs raised. Isometric lower back exercise.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'tuck-crunch',
    name: 'Tuck Crunch',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Simultaneously bring knees and shoulders together in a tucking motion. Targets the full abs.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'windmill',
    name: 'Windmill',
    primary_muscle: 'core',
    secondary_muscles: ['shoulders'],
    description: 'With one arm overhead, hinge sideways at the hip to touch the floor. Builds core stability.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'kettlebell-swing-american',
    name: 'Kettlebell Swing American',
    primary_muscle: 'core',
    secondary_muscles: ['legs', 'shoulders'],
    description: 'Swing a kettlebell from between your legs to overhead in one fluid motion. Full-body power move.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
  {
    id: 'farmers-walk',
    name: "Farmer's Walk",
    primary_muscle: 'core',
    secondary_muscles: ['arms', 'legs', 'shoulders'],
    description: 'Carry heavy weights in each hand and walk. Builds grip strength, core stability, and overall conditioning.',
    image_url: null,
    youtube_url: null,
    category: 'strength',
  },
]

export const EXERCISES_BY_MUSCLE: Record<MuscleGroup, ExerciseEntry[]> = {
  chest: EXERCISES.filter(e => e.primary_muscle === 'chest'),
  back: EXERCISES.filter(e => e.primary_muscle === 'back'),
  legs: EXERCISES.filter(e => e.primary_muscle === 'legs'),
  shoulders: EXERCISES.filter(e => e.primary_muscle === 'shoulders'),
  arms: EXERCISES.filter(e => e.primary_muscle === 'arms'),
  core: EXERCISES.filter(e => e.primary_muscle === 'core'),
}

export function getExerciseById(id: string): ExerciseEntry | undefined {
  return EXERCISES.find(e => e.id === id)
}
