import type { MuscleGroup } from '@/types'

export interface ExerciseEntry {
  id: string
  name: string
  primary_muscle: MuscleGroup
  secondary_muscles: MuscleGroup[]
  description: string
  image_url: string | null
  youtube_url: string | null
  category: 'strength' | 'cardio' | 'flexibility'
}

export const EXERCISES: ExerciseEntry[] = [
  // ── CHEST ────────────────────────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower it to your chest, and press back up.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    category: 'strength',
  },
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Set bench to 30-45°. Press dumbbells up from chest level, focusing on the upper chest.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    category: 'strength',
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms', 'core'],
    description: 'Classic bodyweight push-up. Keep your body in a straight line from head to heels.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    category: 'strength',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    description: 'Set cables at chest height. Bring handles together in a wide arc, squeezing the chest at the peak.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
    category: 'strength',
  },
  {
    id: 'dips',
    name: 'Chest Dips',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'arms'],
    description: 'Lean forward slightly on the dip bars to target the chest. Lower until arms are at 90°.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=wjUmnZH528Y',
    category: 'strength',
  },

  // ── BACK ─────────────────────────────────────────────────────────────────
  {
    id: 'pull-up',
    name: 'Pull-Up',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Hang from a bar with overhand grip. Pull yourself up until chin clears the bar.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    category: 'strength',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms', 'core'],
    description: 'Hinge at hips, keep back flat, pull bar to lower chest. One of the best back builders.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ',
    category: 'strength',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Pull the bar down to upper chest level, leading with elbows. Wide grip targets the lats.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    category: 'strength',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    primary_muscle: 'back',
    secondary_muscles: ['arms'],
    description: 'Sit upright, pull the cable handle to your midsection, squeezing shoulder blades together.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    category: 'strength',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    primary_muscle: 'back',
    secondary_muscles: ['legs', 'core'],
    description: 'Pull the barbell from the floor to hip level. Engages the entire posterior chain.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    category: 'strength',
  },

  // ── LEGS ─────────────────────────────────────────────────────────────────
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Bar on traps, squat to parallel or below. The king of leg exercises.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    category: 'strength',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Press the platform away with both feet at shoulder-width. Control the descent.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    category: 'strength',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    primary_muscle: 'legs',
    secondary_muscles: ['back'],
    description: 'Hinge at hips with soft knees, lowering the bar along your legs. Great for hamstrings.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    category: 'strength',
  },
  {
    id: 'lunges',
    name: 'Dumbbell Lunges',
    primary_muscle: 'legs',
    secondary_muscles: ['core'],
    description: 'Step forward into a lunge, lowering the back knee toward the floor. Alternate legs.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
    category: 'strength',
  },
  {
    id: 'leg-curl',
    name: 'Lying Leg Curl',
    primary_muscle: 'legs',
    secondary_muscles: [],
    description: 'Curl your heels toward your glutes against resistance. Isolates the hamstrings.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
    category: 'strength',
  },

  // ── SHOULDERS ────────────────────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Barbell Overhead Press',
    primary_muscle: 'shoulders',
    secondary_muscles: ['arms', 'core'],
    description: 'Press a barbell from shoulder height straight overhead. Keep core braced throughout.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    category: 'strength',
  },
  {
    id: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: [],
    description: 'Raise dumbbells out to the sides to shoulder height. Targets the medial (side) delt.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    category: 'strength',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    primary_muscle: 'shoulders',
    secondary_muscles: ['back'],
    description: 'Pull a rope attachment to face level, externally rotating shoulders. Great for rear delts.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    category: 'strength',
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    primary_muscle: 'shoulders',
    secondary_muscles: ['arms'],
    description: 'Start with dumbbells at chin with palms facing you, rotate and press overhead.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=6Z15_WdXmVw',
    category: 'strength',
  },

  // ── ARMS ─────────────────────────────────────────────────────────────────
  {
    id: 'bicep-curl',
    name: 'Dumbbell Bicep Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Curl the dumbbells from fully extended to fully contracted, keeping elbows fixed.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    category: 'strength',
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Push a cable bar or rope down until arms are fully extended. Keep elbows at sides.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=2-LAMcpzODU',
    category: 'strength',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Neutral grip curl (thumbs up). Targets both bicep and brachialis for thicker arms.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
    category: 'strength',
  },
  {
    id: 'skull-crushers',
    name: 'Skull Crushers',
    primary_muscle: 'arms',
    secondary_muscles: [],
    description: 'Lower a barbell or dumbbells toward your forehead while lying on a bench. Tricep isolation.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
    category: 'strength',
  },

  // ── CORE ─────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    primary_muscle: 'core',
    secondary_muscles: ['shoulders'],
    description: 'Hold a push-up position on your forearms. Keep hips level and core tight.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    category: 'strength',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Hang from a bar, raise straight legs to 90° (or higher). Targets lower abs.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
    category: 'strength',
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    primary_muscle: 'core',
    secondary_muscles: [],
    description: 'Kneel at a cable with rope attachment overhead, crunch down contracting abs.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=2fbujeH3F0E',
    category: 'strength',
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    primary_muscle: 'core',
    secondary_muscles: ['shoulders', 'back'],
    description: 'Roll the wheel out from kneeling position, extending body, then pull back. Advanced core.',
    image_url: null,
    youtube_url: 'https://www.youtube.com/watch?v=wbsKrGkIx1A',
    category: 'strength',
  },
]

export const EXERCISES_BY_MUSCLE: Record<MuscleGroup, ExerciseEntry[]> = {
  chest: EXERCISES.filter(e => e.primary_muscle === 'chest'),
  back: EXERCISES.filter(e => e.primary_muscle === 'back'),
  legs: EXERCISES.filter(e => e.primary_muscle === 'legs'),
  shoulders: EXERCISES.filter(e => e.primary_muscle === 'shoulders'),
  arms: EXERCISES.filter(e => e.primary_muscle === 'arms'),
  core: EXERCISES.filter(e => e.primary_muscle === 'core'),
}

export function getExerciseById(id: string): ExerciseEntry | undefined {
  return EXERCISES.find(e => e.id === id)
}
